Controllers/FactoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Avram_Maria_Furniture.Data;
using Avram_Maria_Furniture.Models;
using Avram_Maria_Furniture.Models.FurnitureStoreViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Avram_Maria_Furniture.Controllers
{
    public class FactoriesController : Controller
    {
        private readonly FurnitureStoreContext _context;

        public FactoriesController(FurnitureStoreContext context)
        {
            _context = context;
        }

        // GET: Factories
        public async Task<IActionResult> Index(int? id, int? furnitureID)
        {
            var viewModel = new FactoryIndexData();
            viewModel.Factories = await _context.Factories
            .Include(i => i.ManufacturedFurniture)
            .ThenInclude(i => i.Furniture)
            .ThenInclude(i => i.Orders)
            .ThenInclude(i => i.Customer)
            .AsNoTracking()
            .OrderBy(i => i.FactoryName)
            .ToListAsync();
            if (id != null)
            {
                ViewData["FactoryID"] = id.Value;
                Factory factory = viewModel.Factories.Where(
                i => i.ID == id.Value).Single();
                viewModel.Furnitures = factory.ManufacturedFurniture.Select(s => s.Furniture);
            }
            if (furnitureID != null)
            {
                ViewData["FurnitureID"] = furnitureID.Value;
                viewModel.Orders = viewModel.Furnitures.Where(
                x => x.ID == furnitureID).Single().Orders;
            }
            return View(viewModel);
        }

        // GET: Factories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factory = await _context.Factories
                .FirstOrDefaultAsync(m => m.ID == id);
            if (factory == null)
            {
                return NotFound();
            }

            return View(factory);
        }

        // GET: Factories/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Factories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("ID,FactoryName,Address")] Factory factory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(factory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(factory);
        }

        // GET: Factories/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factory = await _context.Factories
                .Include(i => i.ManufacturedFurniture).ThenInclude(i => i.Furniture)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.ID == id);
            if (factory == null)
            {
                return NotFound();
            }
            PopulateManufacturedFurnitureData(factory);
            return View(factory);
        }
        private void PopulateManufacturedFurnitureData(Factory factory)
        {
            var allFurnitures = _context.Furnitures;
            var manufacturedFurnitures = new HashSet<int>(factory.ManufacturedFurniture.Select(c => c.FurnitureID));
            var viewModel = new List<ManufacturedFurnitureData>();
            foreach (var furniture in allFurnitures)
            {
                viewModel.Add(new ManufacturedFurnitureData
                {
                    FurnitureID = furniture.ID,
                    Title = furniture.Title,
                    IsDone = manufacturedFurnitures.Contains(furniture.ID)
                });
            }
            ViewData["Furnitures"] = viewModel;
        }

        // POST: Factories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int? id, string[] selectedFurnitures)
        {
            if (id == null)
            {
                return NotFound();
            }
            var factoryToUpdate = await _context.Factories
            .Include(i => i.ManufacturedFurniture)
            .ThenInclude(i => i.Furniture)
            .FirstOrDefaultAsync(m => m.ID == id);
            if (await TryUpdateModelAsync<Factory>(factoryToUpdate,"",i => i.FactoryName, i => i.Address))
            {
                UpdateManufacturedFurnitures(selectedFurnitures, factoryToUpdate);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException /* ex */)
                {

                    ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists, ");
                }
                return RedirectToAction(nameof(Index));
            }
            UpdateManufacturedFurnitures(selectedFurnitures, factoryToUpdate);
            PopulateManufacturedFurnitureData(factoryToUpdate);
            return View(factoryToUpdate);
        }
        private void UpdateManufacturedFurnitures(string[] selectedFurnitures, Factory factoryToUpdate)
        {
            if (selectedFurnitures == null)
            {
                factoryToUpdate.ManufacturedFurniture = new List<ManufacturedFurniture>();
                return;
            }
            var selectedFurnituresHS = new HashSet<string>(selectedFurnitures);
            var producedFurniture = new HashSet<int>
            (factoryToUpdate.ManufacturedFurniture.Select(c => c.Furniture.ID));
            foreach (var furniture in _context.Furnitures)
            {
                if (selectedFurnituresHS.Contains(furniture.ID.ToString()))
                {
                    if (!producedFurniture.Contains(furniture.ID))
                    {
                        factoryToUpdate.ManufacturedFurniture.Add(new ManufacturedFurniture
                        {
                            FactoryID = factoryToUpdate.ID,
                            FurnitureID = furniture.ID
                        });
                    }
                }
                else
                {
                    if (producedFurniture.Contains(furniture.ID))
                    {
                        ManufacturedFurniture bookToRemove = factoryToUpdate.ManufacturedFurniture.FirstOrDefault(i
                       => i.FurnitureID == furniture.ID);
                        _context.Remove(bookToRemove);
                    }
                }
            }
        }

        // GET: Factories/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var factory = await _context.Factories
                .FirstOrDefaultAsync(m => m.ID == id);
            if (factory == null)
            {
                return NotFound();
            }

            return View(factory);
        }

        // POST: Factories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var factory = await _context.Factories.FindAsync(id);
            _context.Factories.Remove(factory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FactoryExists(int id)
        {
            return _context.Factories.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Furniture Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>Furniture Store</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 navbar-right">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Furnitures" asp-action="Index">Furnitures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Factories" asp-action="Index">Factories</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Statistics">Statistics</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Chat">Chat</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Avram_Maria_Furniture - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>